version: '3.9'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./app:/var/www/html
    environment:
      - DB_HOST=postgres
      - DB_NAME=monde_db
      - DB_USER=postgres
      - DB_PASS=postgres
      - TINYMCE_API_KEY=${TINYMCE_API_KEY}
      - TZ=Africa/Cairo

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=monde_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Africa/Cairo
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: