server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;
    index index.php index.html;

    # Permettre l'accès aux fichiers dans le dossier /uploads à la racine du projet
    location /uploads/ {
        # Revenir au comportement par défaut pour les images uploadées 
        # (elles sont maintenant dans le dossier public)
        try_files $uri $uri/ =404;
        expires 30d;
        access_log off;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}